# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(350, 10, 231, 81))
        self.title_label.setAutoFillBackground(False)
        self.title_label.setStyleSheet("font: 28pt \"AcadEref\";\n"
"color: rgb(255, 0, 0);")
        self.title_label.setObjectName("title_label")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(60, 260, 241, 81))
        self.output_label.setStyleSheet("font: 20pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.output_label.setObjectName("output_label")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 340, 441, 191))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.output_gragh_label = QtWidgets.QLabel(self.centralwidget)
        self.output_gragh_label.setGeometry(QtCore.QRect(560, 260, 161, 81))
        self.output_gragh_label.setStyleSheet("font: 20pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.output_gragh_label.setObjectName("output_gragh_label")
        self.promote_label = QtWidgets.QLabel(self.centralwidget)
        self.promote_label.setGeometry(QtCore.QRect(60, 80, 191, 81))
        self.promote_label.setStyleSheet("font: 20pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.promote_label.setObjectName("promote_label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 160, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.promote_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.promote_label_2.setGeometry(QtCore.QRect(70, 140, 61, 61))
        self.promote_label_2.setStyleSheet("font: 30pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.promote_label_2.setObjectName("promote_label_2")
        self.promote_label_3 = QtWidgets.QLabel(self.centralwidget)
        self.promote_label_3.setGeometry(QtCore.QRect(300, 80, 191, 81))
        self.promote_label_3.setStyleSheet("font: 20pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.promote_label_3.setObjectName("promote_label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 160, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 160, 91, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 200, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 200, 91, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.promote_label_4 = QtWidgets.QLabel(self.centralwidget)
        self.promote_label_4.setGeometry(QtCore.QRect(560, 80, 191, 81))
        self.promote_label_4.setStyleSheet("font: 20pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.promote_label_4.setObjectName("promote_label_4")
        self.promote_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.promote_label_5.setGeometry(QtCore.QRect(560, 130, 171, 81))
        self.promote_label_5.setStyleSheet("font: 14pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.promote_label_5.setObjectName("promote_label_5")
        self.promote_label_6 = QtWidgets.QLabel(self.centralwidget)
        self.promote_label_6.setGeometry(QtCore.QRect(560, 170, 171, 81))
        self.promote_label_6.setStyleSheet("font: 14pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.promote_label_6.setObjectName("promote_label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(730, 160, 61, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(730, 200, 61, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(730, 240, 61, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.promote_label_7 = QtWidgets.QLabel(self.centralwidget)
        self.promote_label_7.setGeometry(QtCore.QRect(560, 210, 171, 81))
        self.promote_label_7.setStyleSheet("font: 14pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.promote_label_7.setObjectName("promote_label_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(840, 160, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.output_gragh_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.output_gragh_label_2.setGeometry(QtCore.QRect(770, 260, 161, 81))
        self.output_gragh_label_2.setStyleSheet("font: 20pt \"AcadEref\";\n"
"color: rgb(0, 0, 0);")
        self.output_gragh_label_2.setObjectName("output_gragh_label_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(550, 340, 191, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(770, 340, 191, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "GMM-EM算法"))
        self.output_label.setText(_translate("MainWindow", "指令执行运行结果："))
        self.output_gragh_label.setText(_translate("MainWindow", "2D-聚类结果"))
        self.promote_label.setText(_translate("MainWindow", "请选择数据集："))
        self.pushButton.setText(_translate("MainWindow", "选择"))
        self.promote_label_2.setText(_translate("MainWindow", "…"))
        self.promote_label_3.setText(_translate("MainWindow", "数据处理："))
        self.pushButton_2.setText(_translate("MainWindow", "查看异常值"))
        self.pushButton_3.setText(_translate("MainWindow", "查看重复值"))
        self.pushButton_4.setText(_translate("MainWindow", "查看数据统计"))
        self.pushButton_5.setText(_translate("MainWindow", "保存"))
        self.promote_label_4.setText(_translate("MainWindow", "聚类分析："))
        self.promote_label_5.setText(_translate("MainWindow", "输入聚类数量／个："))
        self.promote_label_6.setText(_translate("MainWindow", "输入迭代次数／次："))
        self.promote_label_7.setText(_translate("MainWindow", "输入相差阈值："))
        self.pushButton_6.setText(_translate("MainWindow", "开始分析"))
        self.output_gragh_label_2.setText(_translate("MainWindow", "3D-聚类结果"))


import sys
if __name__ == '__main__':
   app = QtWidgets.QApplication(sys.argv)
   MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
   ui = Ui_MainWindow() # 创建PyQt设计的窗体对象
   ui.setupUi(MainWindow) # 调用PyQt窗体的方法对窗体对象进行初始化设置
   MainWindow.show() # 显示窗体
   sys.exit(app.exec_()) # 程序关闭时退出进程